name: Linting

on:
  pull_request:
    branches:
      - '*' 
  push:
    branches:
      - main 

jobs:
  lint:
    name: Run Lint Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run Prettier Check
        run: npx prettier --check .
